### ISSUE TITLE
StreamingSubscriptionConnection.OnDisconnect never called

### ISSUE THREAD

**Issue by gerneio** [ItsClemi/ews-managed-api#8]
Given example below, `OnDisconnect` event is never called (other events do appear to work, **_within lifetime boundary_**, just not afterwards) Checking `IsOpen` after the one minute lifetime shows it is still open. Subsequently trying to call `Close()` results in a hanged process.

```C#
EventType[] events = [ EventType.NewMail, EventType.Deleted, EventType.Modified, EventType.Moved, EventType.Copied, EventType.Created, EventType.FreeBusyChanged ];
var sub = await service.SubscribeToStreamingNotificationsOnAllFolders(eventTypes: events);

var conn = new StreamingSubscriptionConnection(service, 1); // Lifetime = one min
conn.AddSubscription(sub);

conn.OnNotificationEvent += Conn_OnNotificationEvent;
conn.OnDisconnect += Conn_OnDisconnect; // Never called. Should be called one min after calling Open();
conn.OnSubscriptionError += Conn_OnSubscriptionError;

conn.Open();

// Shouldn't need this, but also doesn't work
Task.Delay(2000).ContinueWith((t) => {
    Console.WriteLine(conn.IsOpen);

    if (conn.IsOpen)
        conn.Close(); // Hangs
    // ... reopen?
});
```

Alternatively, what will work is manually detecting when the lifetime is passed, disposing the current connection, and re-creating a new connection. Not sure if there are any side affects with this approach, but it does appear to work.

**Comment by ItsClemi** [comment]
Hi, thanks for reaching out and sorry for responding so late - Github didn't send me an email notification, even thou this is my own repo? what?!..

Anyways, in your example the `StreamingSubscriptionConnection` is not properly disposed due to a missing `using`: 
```csharp
using var conn = new StreamingSubscriptionConnection(service, 1); // Lifetime = one min
```
But even if you supplied it the outcome would probably be the same as the original code didn't close the connection in the dispose function at all [original code](https://github.com/OfficeDev/ews-managed-api/blob/master/Notifications/StreamingSubscriptionConnection.cs#L468). So to get the OnDisconnect event you'd have to manually call `conn.Close()`. 

I've changed this behavior in #14 - so if you dispose the `StreamingSubscriptionConnection` the client disconnections automatically.

For the hang, I think this is intended EWS behavior?! In my test example, the client also hanged for about 30 seconds but then continued operation. Also to change the `closing` behavior to continue immediately on `.Close()`, I'd have to modify some of the XML parsing code as the client effectively blocks on `XmlReader.ReadAsync()` which doesn't support cancellation.
